name: Generate and Deploy Dokka Docs

on:
  push:
    branches:
      - main

jobs:
  deploy-dokka:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle.lockfile') }}
          restore-keys: gradle-

      - name: Generate Dokka HTML
        run: ./gradlew dokkaHtml

      - name: Clone existing gh-pages branch
        run: |
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Dokka output into gh-pages/dokka/
        run: |
          rm -rf gh-pages/dokka
          mkdir -p gh-pages/dokka
          cp -r build/dokka/html/* gh-pages/dokka/

      - name: Commit and push Dokka docs
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dokka
          git commit -m "Update Dokka docs on push to main" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
