name: Build and Deploy Javadoc

on:
  push:
    branches:
      - main  # oder master, je nachdem, was du nutzt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22


      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle.lockfile') }}
          restore-keys: gradle-


      -  name: Make gradlew executable
         run: chmod +x ./gradlew

      - name: Build project and generate Javadoc
        run: ./gradlew clean javadoc

      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc
